clear

Course = imread('map 2.jpg');
Blank = imread('blank2.jpg');
[BW,maskedRGBImage] = createMask(Course);

subplot(2,2,1),imshow(Course); title('course')
subplot(2,2,2),imshow(Blank); title('blank')
subplot(2,2,3),imshow(maskedRGBImage); title('course isolated')
subplot(2,2,4),imshow(BW); title('course b&w')
figure;imshow(BW);
axis on;
hold on
[c, r, m] = imfindcircles(BW,[20, 40]);

control1 = [c(1),c(4)];
control2 = [c(2),c(5)];
control3 = [c(3),c(6)];
x1 = c(1);
y1 = c(4);
x2 = c(2);
y2 = c(5);
x3 = c(3);
y3 = c(6);

viscircles(c, r,'EdgeColor','r','linestyle','-');
plot(x1,y1, 'r+', 'MarkerSize', 10, 'LineWidth', 1);
plot(x2,y2, 'r+', 'MarkerSize', 10, 'LineWidth', 1);
plot(x3,y3, 'r+', 'MarkerSize', 10, 'LineWidth', 1);
hold off

imshow('blank2.jpg')
hold on
viscircles([x1, y1], r(1));
viscircles([x2, y2], r(1));
viscircles([x3, y3], r(1));
plot(x1, y1, 'r+', 'MarkerSize', 10, 'LineWidth', 1);
plot(x2, y2, 'r+', 'MarkerSize', 10, 'LineWidth', 1);
plot(x3, y3, 'r+', 'MarkerSize', 10, 'LineWidth', 1);
plot([x1,x2],[y1, y2],'lineWidth', 3, 'lineStyle', '-', 'Color', 'r');
plot([x2,x3],[y2, y3],'lineWidth', 3, 'lineStyle', '-', 'Color', 'r');
axis on;

function [BW,maskedRGBImage] = createMask(RGB)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder app. The colorspace and
%  range for each channel of the colorspace were set within the app. The
%  segmentation mask is returned in BW, and a composite of the mask and
%  original RGB images is returned in maskedRGBImage.

% Auto-generated by colorThresholder app on 16-Jan-2021
%------------------------------------------------------


% Convert RGB image to chosen color space
I = RGB;

% Define thresholds for channel 1 based on histogram settings
channel1Min = 102.000;
channel1Max = 255.000;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 0.000;
channel2Max = 140.000;

% Define thresholds for channel 3 based on histogram settings
channel3Min = 150.000;
channel3Max = 240.000;

% Create mask based on chosen histogram thresholds
sliderBW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
BW = sliderBW;

% Initialize output masked image based on input image.
maskedRGBImage = RGB;

% Set background pixels where BW is false to zero.
maskedRGBImage(repmat(~BW,[1 1 3])) = 0;

end
